### ISSUE TITLE
Optional background color for preformatted text

### ISSUE THREAD

**Issue by makew0rld** [makew0rld/amfora#279]
Sometimes it's hard to distinguish between preformatted text and regular text on Gemini. Some themes fix this by making preformatted text a different color, but not all themes do that, especially the default theme. And when you throw #252 into the mix it gets more confusing. A good way to solve this would be an optional background color for preformatted text. It would just be another theme key, but if unset or set to `"default"` it would use the same value as the `bg` key.

**Comment by makeworld-the-better-one** [comment]
Added to the v1.10.0 milestone because #252 is in there as well.

**Comment by makeworld-the-better-one** [comment]
Ideally the background color would have some sort of padding, so that it doesn't begin right on the edge of the letter, but one space above and to left for the first letter, etc. Like this area for GitHub code blocks that I've highlighted:

![image](https://user-images.githubusercontent.com/25111343/145643801-1268e950-91d8-46b7-a832-06c6c7f0c64a.png)

Doing this vertically is a super easy change. Doing it horizontally would probably require a lot of rendering or layout refactoring, so it depends on how bad it looks without it I guess.

**Comment by makew0rld** [comment]
I am closing all stale non-bug issues so this issue will be closed. However a PR for this could still be accepted.
