### ISSUE TITLE
New releases scheduled?

### ISSUE THREAD

**Issue by stkw0** [makew0rld/amfora#339]
Is a new release planned? The last release is from 2021 and since then seems that there are important fixes. Thanks.

**Comment by makew0rld** [comment]
Amfora is currently in [maintenance mode](https://github.com/makew0rld/amfora#project-status). I would like to make a new release but I don't have a specific plan for one at the moment. Is there a specific fix you had in mind that you would like to see released?

Note that it's always possible to build and install from the latest commit.

**Comment by stkw0** [comment]
I missed that bit about this project being in maintenance mode. Sorry.  
About the fixes, I misread one of the issues, I thought this project was not able to be compiled with go >1.17 but the issue was with older versions so it's not that important.

**Comment by svmhdvn** [comment]
It would be nice to get an up-to-date release so that all distributions that currently package amfora receive all the latest fixes. Now that amfora is in maintenance mode, this new release can serve as "the final release" for the time being. I feel that there have been enough commits since 2021 to justify this.

**Comment by makew0rld** [comment]
Yes, you're probably right. I don't have a timeline for this but I'll put it on my list.
